"""Behavior aggregation, retrieval, and recommendation ranking."""

from myusic_engine.ranking.behavior import (
    AffinityConfig,
    BehaviorAggregationError,
    TrackAffinity,
    aggregate_track_behavior,
    load_affinity_config,
    load_duration_map,
    score_affinity,
    write_track_affinities,
)
from myusic_engine.ranking.candidates import (
    CandidateInputError,
    CandidateTrack,
    read_candidates,
    spotify_uri,
)
from myusic_engine.ranking.feedback import (
    FeedbackError,
    RecommendationFeedback,
    append_feedback,
    create_feedback,
    read_feedback,
)
from myusic_engine.ranking.recommendations import (
    RankedRecommendation,
    RecommendationConfig,
    RecommendationError,
    RecommendationReport,
    RecommendationResult,
    load_recommendation_config,
    rank_candidates,
    write_recommendations,
)
from myusic_engine.ranking.similarity import (
    CategoricalFilter,
    EmbeddingSpec,
    FilterEvidence,
    NumericRangeFilter,
    SimilarityError,
    SimilarityFilter,
    SimilarityIndex,
    SimilarityMatch,
    weighted_query_embedding,
)

__all__ = [
    "AffinityConfig",
    "BehaviorAggregationError",
    "CategoricalFilter",
    "CandidateInputError",
    "CandidateTrack",
    "EmbeddingSpec",
    "FeedbackError",
    "FilterEvidence",
    "NumericRangeFilter",
    "RankedRecommendation",
    "RecommendationConfig",
    "RecommendationError",
    "RecommendationFeedback",
    "RecommendationReport",
    "RecommendationResult",
    "SimilarityError",
    "SimilarityFilter",
    "SimilarityIndex",
    "SimilarityMatch",
    "TrackAffinity",
    "aggregate_track_behavior",
    "append_feedback",
    "create_feedback",
    "load_affinity_config",
    "load_duration_map",
    "load_recommendation_config",
    "rank_candidates",
    "read_candidates",
    "read_feedback",
    "score_affinity",
    "spotify_uri",
    "write_track_affinities",
    "weighted_query_embedding",
    "write_recommendations",
]
