"""Leakage-safe personal taste dataset construction and model training."""

from myusic_engine.modeling.config import (
    AudioFeatureProfile,
    AudioInputSpec,
    ModelingConfig,
    ModelingConfigError,
    TasteModelConfig,
    TemporalConfig,
    load_modeling_config,
)
from myusic_engine.modeling.representation import (
    ProfiledFeatureCatalog,
    RepresentationError,
    TrackAudioRepresentation,
)
from myusic_engine.modeling.temporal import (
    BEHAVIOR_FEATURE_NAMES,
    BehaviorSnapshot,
    TemporalDatasetError,
    TemporalDatasetReport,
    TemporalDatasetResult,
    TemporalTasteSample,
    artist_key,
    build_temporal_dataset,
    read_behavior_snapshots,
    read_temporal_samples,
    write_temporal_dataset,
)
from myusic_engine.modeling.training import (
    LinearTasteModel,
    TastePrediction,
    TasteTrainingError,
    TasteTrainingReport,
    TasteTrainingResult,
    VariantEvaluation,
    model_input_vector,
    read_taste_model,
    train_taste_models,
    write_taste_training_result,
)

__all__ = [
    "AudioFeatureProfile",
    "AudioInputSpec",
    "BEHAVIOR_FEATURE_NAMES",
    "BehaviorSnapshot",
    "LinearTasteModel",
    "ModelingConfig",
    "ModelingConfigError",
    "ProfiledFeatureCatalog",
    "RepresentationError",
    "TasteModelConfig",
    "TastePrediction",
    "TasteTrainingError",
    "TasteTrainingReport",
    "TasteTrainingResult",
    "TemporalConfig",
    "TemporalDatasetError",
    "TemporalDatasetReport",
    "TemporalDatasetResult",
    "TemporalTasteSample",
    "TrackAudioRepresentation",
    "VariantEvaluation",
    "artist_key",
    "build_temporal_dataset",
    "load_modeling_config",
    "model_input_vector",
    "read_behavior_snapshots",
    "read_temporal_samples",
    "read_taste_model",
    "train_taste_models",
    "write_taste_training_result",
    "write_temporal_dataset",
]
